name: apps-workspace

packages:
  - shared/*
  - modules/*
  - apps/*

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true
    environment:
      sdk: ">=3.0.0 <4.0.0"
    dependencies:
      drift: ^2.19.1+1
      get_it: ^7.7.0
      injectable: ^2.4.4
      sqlite3: ^2.4.3
      sqlite3_flutter_libs: ^0.5.24
      path_provider: ^2.1.3
      path: ^1.9.0

    dev_dependencies:
      build_runner: ^2.4.9
      drift_dev: ^2.19.1
      flutter_test:
        sdk: flutter
      injectable_generator: ^2.6.2
      test: ^1.24.9
      flutter_lints: ^4.0.0


  version:
    linkToCommits: false
    branch: main
    workspaceChangelog: true

scripts:   
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 1 -- \
        flutter analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.

  format-check:
    run: melos exec --ignore="*apps_translations*" dart format . --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  test:select:
    run: melos exec -c 1 -- flutter test
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.


  generate:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 3
      orderDependents: true
      failFast: true
    packageFilters:
      dependsOn:
        - build_runner
    description: Run code generation using build_runner in a specific package
  
  generate:debug:
    run: dart run build_runner build --delete-conflicting-outputs --verbose
    exec:
      orderDependents: true
      failFast: true
    packageFilters:
      dependsOn:
        - build_runner
    description: Run code generation using build_runner in a specific package in debug mode

  generate:watch:
    run: dart run build_runner watch --delete-conflicting-outputs
    exec:
      orderDependents: true
      failFast: true
    packageFilters:
      dependsOn:
        - build_runner
    description: Run code generation using build_runner in a specific package, and watch any changes in this package

  generate:clean:
    run: dart run build_runner clean
    exec:
      concurrency: 1
      orderDependents: true
      failFast: true
    packageFilters:
      dependsOn:
        - build_runner
    description: Run code generation clean using build_runner in a specific package

  packages:update:
    run: flutter pub upgrade --major-versions --tighten
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - lib
    description: Run update packages.


