name: apps-workspace

packages:
  - shared/*
  - modules/*
  - apps/*

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true
    environment:
      sdk: ">=3.0.0 <4.0.0"
    dependencies:
      drift: ^2.14.0
      get_it: ^7.6.4
      injectable: ^2.3.2
      sqlite3: ^2.1.0
      sqlite3_flutter_libs: ^0.5.0
      path_provider: ^2.0.0
      path: ^1.8.3

    dev_dependencies:
      build_runner: ^2.4.8
      drift_dev: ^2.14.0
      flutter_test:
        sdk: flutter
      injectable_generator: ^2.4.1
      test: ^1.24.3
      flutter_lints: ^2.0.0


  version:
    linkToCommits: false
    branch: main
    workspaceChangelog: true

scripts:   
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 1 -- \
        flutter analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.

  format-check:
    run: melos exec --ignore="*apps_translations*" dart format . --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  test:select:
    run: melos exec -c 1 -- flutter test
    ignore:
      'packages/shared/apps_translations'
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.

  coverage:
    run: |
      melos exec -- flutter test --coverage
    ignore:
      'packages/shared/apps_translations'
    packageFilters:
      dirExists: test
    description: Generate coverage for the selected package.


  generate:
    run: melos exec --concurrency=2 --fail-fast --order-dependents --depends-on="build_runner" -- dart pub run build_runner build --delete-conflicting-outputs
    description: Run all build_runner in this project.

  generate:clean:
    run: melos exec --depends-on="build_runner" -- dart pub run build_runner clean
    description: Run clean build_runner in this project.


