name: storage
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.23.1
  sqlite3: ^2.7.2
  sqlite3_flutter_libs: ^0.5.29+1
  path_provider: ^2.1.5
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  drift_dev: ^2.23.1
  test: ^1.25.7
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
