targets:
  $default:
    builders:
      drift_dev:
        enabled: false
      drift_dev:analyzer:
        enabled: true
        generate_for: &drift_generate_for
          include:
            - lib/data/**.dart
          exclude:
            - lib/data/**.*.dart
        options: &options
          # Drift build options, as per https://drift.simonbinder.eu/docs/advanced-features/builder_options/
          store_date_time_values_as_text: true
          named_parameters: true
          sql:
            dialect: sqlite
            options:
              version: "3.44"
              modules: [fts5]
      drift_dev:modular:
        enabled: true
        generate_for: *drift_generate_for
        options: *options
      injectable_generator:injectable_builder:
        generate_for: &injectable_generate_for
          include:
            - lib/**.dart
      injectable_generator:injectable_config_builder:
        generate_for: *injectable_generate_for