include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: [build/**, test/**.mocks.dart, lib/**.g.dart, lib/**.config.dart, lib/**.drift.dart, test/**.drift.dart, bricks/**.dart]
  language:
    strict-casts: true
    strict-raw-types: false
  errors:
    non_constant_identifier_names: ignore
